# base image
FROM python:3.11-slim

WORKDIR /app

# install pg_isready
RUN apt-get update && \
    apt-get install -y postgresql-client && \
    rm -rf /var/lib/apt/lists/*

# install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

# dev server with reload and migrations
ENTRYPOINT ["bash", "/app/entrypoint.sh"]