CATEGORY_MAP = {
    "skincare": {
        # --- original ---
        "en:skin", "en:face", "en:face-creams", "en:moisturizers",
        "en:suncare", "en:sun-protection", "en:sunscreen",
        "en:serums", "en:cleansers", "en:toners",
        "en:body-lotions", "en:hand-creams", "en:eye-creams",
        "en:acne", "en:anti-aging",
        # --- round 1 expansion ---
        "en:showers-and-baths", "en:shower-gels",
        "en:deodorants", "en:soaps", "en:body",
        "en:facial-creams", "en:body-creams", "en:body-milks",
        "en:shaving", "en:roll-on-deodorants", "en:anti-perspirants",
        "en:in-sun-protections", "en:liquid-soaps", "en:body-wash",
        "en:hand-wash", "en:hand-soap", "en:bar-soap",
        "en:baby-oil", "en:bubble-baths",
        "en:body-scrubs", "en:body-butters", "en:body-powders",
        "en:lip-balms", "en:massage-oil",
        # --- round 2 expansion (max coverage) ---
        # face care
        "en:face-wash", "en:face-lotions", "en:face-scrubs",
        "en:face-masks", "en:face-cleanser", "en:face-serum",
        "en:facial-cleansers", "en:facial-wash", "en:facial-serum",
        "en:day-creams", "en:night-creams", "en:day-and-night-creams",
        "en:anti-aging-face-care-products", "en:anti-wrinkles-creams",
        "en:cleansing-milks", "en:cleansing-waters", "en:cleansing-lotion",
        "en:cleansing-bar", "en:micellar-water",
        "en:make-up-remover", "en:eye-makeup-remover",
        "en:toner", "en:serum",
        "en:moisturizer", "en:moisturiser",
        "en:lotion", "en:creams", "en:cream",
        "en:defining-cream", "en:creme-hydratante",
        "en:self-tanner", "en:tan-preparers",
        "en:rough-clay", "en:direct-acids", "en:retinoids",
        "en:sensitive", "en:savon-exfoliant",
        "en:gommages-visage", "en:masques-visage", "en:masque-visage",
        "en:points-noirs", "en:poudre-matifiante", "en:wattepad",
        "en:visage", "en:visage-et-corps",
        "en:skin-care", "en:skincare",
        "en:Skin care", "en:Face care", "en:Moisturizers",
        "en:Neck creams", "en:Body care",
        "en:face-moisturiser", "en:face-moisturizer",
        "en:face-cream", "en:facial-mask",
        "en:facial-oil", "en:facial-toner", "en:facial-wipes",
        # body care
        "en:body-oils", "en:body-lotion", "en:body-gels",
        "en:bath-salts", "en:bodycare",
        "en:hand-care", "en:hand-mask", "en:hand-scrub",
        "en:hand-cream", "en:hand-creme",
        "en:cremes-douche", "en:cremes-pour-le-corps",
        "en:cremes-pour-les-pieds", "en:huile-de-douche",
        "en:in-shower-body-lotion", "en:bath-cream",
        "en:body-balm", "en:body-splash", "en:body-wash-cucumber-green-tea",
        "en:corps", "en:mains", "en:corps-et-cheveux",
        "en:body-lotions", "en:body-serum", "en:bath-and-body",
        "en:Body lotions", "en:Body moisturizers",
        "en:Body soaps", "en:Body wash", "en:body-hygiene-liquid",
        "en:body-soap", "en:hand-body-lotion", "en:hand-body-wash",
        "en:body-oil", "en:body-butter",
        # soaps & hygiene
        "en:marseille-soaps", "en:aleppo-soaps", "en:glycerine-soap",
        "en:savons", "en:liquid-soap", "en:flussigseife",
        "en:savon-pour-les-mains", "en:dermatological-soaps",
        "en:bar-soaps", "en:soap", "en:seife",
        "en:gel-douche", "en:gels-douche", "en:duschgele",
        "en:douche", "en:douches-et-bains",
        "en:intimate-hygiene", "en:hygiene-intime",
        "en:intimate-wash-gels",
        # deodorants
        "en:deodorants-anti-transpirants", "en:deodorants-sticks",
        "en:deodrant", "en:bodyspray", "en:deodorant",
        "en:Body deodorants", "en:Crystal deodorants",
        "en:Mineral deodorants", "en:Stick deodorants",
        "en:Spray deodorants", "en:anti-perspirant",
        # shaving
        "en:shaving-gel", "en:shaving-foam", "en:shaving-soaps",
        "en:aftershaves", "en:razors", "en:razor-blades",
        "en:mousse-a-raser", "en:rasage",
        # sun care
        "en:solar-cream", "en:apres-solaires", "en:apres-soleil",
        "en:protections-solaires", "en:solaire", "en:soin-solaire",
        "en:spf-50", "en:uvb", "en:anti-inconforts",
        "en:facial-sunscreens", "en:sunscreen-cream",
        # hair removal
        "en:hair-removal", "en:hair-remover",
        "en:depilatory-wax", "en:cold-depilatory-wax",
        "en:face-depilatory-wax", "en:cire", "en:cire-froide",
        "en:lotion-post-epilation",
        # wipes & baby
        "en:moist-wipes", "en:baby-wipes", "en:wet-wipes",
        "en:bebe", "en:baby-products", "en:bath-shampoo",
        "en:baby-cream", "en:baby-lotion", "en:baby-wash",
        # sanitizers
        "en:hydro-alcoholic-gels", "en:gel-disinfettante",
        "en:gel-desinfectant", "en:hand-sanitizer",
        "en:hand-sanitizers",
        # massage & other
        "en:massage", "en:massage-corps",
        "en:personal-care", "en:skin-care-tools",
        "en:hand-wash-liquid-soaps", "en:shower-cream",
        "en:shower-milk", "en:body-peeling",
        "en:foot-cream", "en:foot-care",
        "en:body-mist", "en:body-spray",
        "en:baby-powder", "en:talcum-powder",
        "en:cotton-buds", "en:tonic",
        # additional variants (singular, case, etc.)
        "en:handwash", "en:Hand care",
        "en:eye-cream", "en:facial-cleanser",
        "en:skin-cream", "en:savon",
        "en:bubble-bath", "en:bath-body",
        "en:petroleum-jelly", "en:petroleum-jellies",
        "en:Personal care", "en:Bath and shower",
        "en:Skincare", "en:body-butter",
        "en:bath-brushes", "en:bath-sponges-loofahs",
        "en:loofahs", "en:exfoliating-gloves",
    },
    "makeup": {
        # --- original ---
        "en:makeup", "en:foundation", "en:lipstick", "en:mascara",
        "en:eyeshadow", "en:eyeliner", "en:blush", "en:concealer",
        "en:nail-polish", "en:bb-cream", "en:primer",
        # --- round 1 expansion ---
        "en:face-makeup", "en:nail-makeup", "en:eyes-makeup",
        "en:lip-cosmetics", "en:lip-gloss",
        "en:foundations", "en:lipsticks", "en:eyeliners",
        "en:eyeshadows", "en:liquid-eyeliner",
        "en:eye-pencils", "en:kohl-pencils",
        "en:bronzer", "en:setting-spray",
        "en:loose-powder", "en:face-powder", "en:powder-foundation",
        "en:cc-creams", "en:dd-creams",
        # --- round 2 expansion (max coverage) ---
        # eye makeup
        "en:eyes", "en:eye-makeup", "en:eye-liner",
        "en:silver-eyeliner", "en:eye-shadow",
        "en:mascaras", "en:eyelash-treatment",
        "en:false-eyelashes", "en:false-nails",
        # lip makeup
        "en:lip-makeup", "en:Make-up", "en:make-up",
        "en:Lip glosses", "en:pink-lipstick",
        "en:lip-stickers", "en:lip-liner",
        "en:lip-plumper", "en:lip-tint",
        "en:lipstick", "en:lip-gloss",
        # nail products
        "en:nail-products", "en:nail-polishes",
        "en:nail-polish-remover", "en:nail-varnish",
        "en:vernis-a-ongles", "en:top-coat",
        "en:nail-polish-removers",
        # complexion
        "en:fonds-de-teint", "en:maquillage",
        "en:maquillage-pour-le-teint", "en:fond-de-teint",
        "en:teint", "en:maquillaje",
        "en:cosmetic-foundations", "en:cosmeticos",
        "en:makeup-base", "en:beauty-foundation",
        # other
        "en:glitter", "en:lip-crayons",
        "en:highlighters", "en:highlighter",
        "en:setting-powders", "en:compact-powder",
        "en:baked-blush", "en:powder-blush",
        "en:cream-blush", "en:liquid-blush",
        "en:makeup-tools", "en:make-up-accessories",
        "en:Lip make-up", "en:Face make-up",
        "en:Makeup accessories",
        "en:eye-concealers", "en:eye-concealer",
        "en:contour", "en:contouring",
        "en:illuminator", "en:shimmer",
        "en:makeup-fixing-spray",
        "en:bb-creams", "en:cc-cream", "en:tinted-moisturizer",
    },
    "haircare": {
        # --- original ---
        "en:hair", "en:shampoos", "en:conditioners",
        "en:hair-treatments", "en:hair-oils", "en:hair-masks",
        "en:styling-gels", "en:hairag", "en:hairoc",
        # --- round 1 expansion ---
        "en:hair-care", "en:hair-conditioners",
        "en:2-in-1-shampoos", "en:anti-dandruff-shampoos",
        "en:hair-dyes", "en:dry-shampoos",
        "en:hair-sprays", "en:hair-gel", "en:hair-mousse",
        "en:solid-shampoos", "en:hair-conditioners-for-dry-hair",
        # --- round 2 expansion (max coverage) ---
        # shampoo variants
        "en:shampoo", "en:shampoo-for-dry-hair",
        "en:shampoo-for-damaged-hair", "en:shampoo-for-fragile-hair",
        "en:shampoos-for-colored-hair", "en:shampoos-for-babies",
        "en:shampoos-for-oily-hair", "en:shampoos-for-children",
        "en:shampoos-conditioners", "en:shampoos-shower-gels",
        "en:shampoings", "en:shampoings-pour-cheveux-secs",
        "en:natural-extract-shampoos", "en:fortifying-shampoos",
        "en:nettle-shampoos", "en:dry-shampoo",
        "en:solid-shampoo", "en:baby-shampoo",
        "en:shampoo-conditioner", "en:shampooing",
        "en:anti-dandruff-shampoo",
        # conditioner variants
        "en:conditioner", "en:hair-conditioner",
        "en:hair-conditioners-for-colored-hair",
        "en:hair-conditioners-for-damaged-hair",
        "en:hair-conditioners-for-regular-hair",
        "en:apres-shampoings", "en:apres-shampoing",
        "en:leave-in-conditioner", "en:Leave-in conditioners",
        # hair styling
        "en:hair-cream", "en:hair-gel",
        "en:hair-pomade", "en:hair-mist",
        "en:hair-perfume", "en:hair-spray",
        "en:hairstyling-foam", "en:hair-styling",
        "en:styling", "en:coiffure",
        "en:sea-salt-spray", "en:hair-tonic",
        "en:hair-straightening", "en:lissage",
        "en:lissage-des-cheveux", "en:defrisage",
        "en:hair-wax", "en:hair-lacquer",
        # treatments
        "en:hair-treatment", "en:hair-treatments",
        "en:silk-therapy", "en:soin-cheveux",
        "en:soins-cheveux", "en:cheveux",
        "en:cure-soyeuse", "en:curesoyeuse",
        "en:royal-silk", "en:royalsilk", "en:soie-royale",
        "en:baume-demelant-nourrissant-argan-carthame",
        "en:wax-out-charcoal-shampoo",
        "en:kopfhaut-kur", "en:maska-do-skory-głowy", "en:wcierka",
        "en:hair-oil", "en:hair-repair",
        "en:hair-mask", "en:hair-care-cream",
        "en:leave-in-treatment", "en:scalp-treatment",
        # coloring
        "en:hair-colorants", "en:hair-dye",
        "en:Hair colorants", "en:Semi-permanent hair dyes",
        "en:colorations-capillaires", "en:developer",
        "en:lightener", "en:bleaching-gels",
        "en:permanent-hair-dyes", "en:Permanent hair dyes",
        # misc
        "en:hairdresser", "en:hairtherapy",
        "en:haircare", "en:Haircare",
        "en:hair-body-care", "en:hair-and-body-wash",
        "en:hair-products", "en:shampoo-all-hair-types",
        "en:shampoo-showergel", "en:shower-shampoo",
        "en:haar", "en:haarpflege",
        "en:3-in-1-shampoos",
    },
}
