export const affirmations: string[] = [
  "Your skin is doing its best, and so are you.",
  "That's a face worth looking at.",
  "You're allowed to like what you see.",
  "Your skin tells a story of showing up for yourself.",
  "Consistency looks good on you.",
  "You don't need filtered skin to feel good in your own.",
  "Your glow isn't about perfect, it's about cared for.",
  "Look closer. You're doing better than you think.",
  "Your reflection deserves kindness, not critique.",
  "Bare-faced or full glam, you're worth looking at.",
  "Your skin is a work in progress, and that's okay.",
  "Some days are good skin days. This can be one.",
  "You're not behind, you're just getting started.",
  "Texture, pores, and all, you're still worth it.",
  "Confidence looks better than any product ever will.",
  "Your skin doesn't have to be perfect to be yours.",
  "Take a second. You look good today.",
  "Progress on your skin is still progress.",
  "Your face has earned some patience today.",
  "You're allowed to feel pretty on an off day.",
  "That mirror doesn't get the final say.",
  "Your skin's healing, even on days it doesn't show.",
  "You don't need a filter to feel like yourself.",
  "Small steps, same face, still worth it.",
  "Your skin is yours to love, not to fix.",
  "Bad skin day, still a good you day.",
  "You're glowing in ways a mirror can't always catch.",
  "Your reflection is trying its best too.",
  "You're worth showing up for, breakouts and all.",
];
