export const affirmations: string[] = [
  "Your skin is doing its best, and so are you.",
  "That's a face worth looking at.",
  "You're allowed to like what you see.",
  "Your skin tells a story of showing up for yourself.",
  "Consistency looks good on you.",
  "You can feel good in your own skin, no filter needed.",
  "Your glow isn't about being perfect, it's about being cared for.",
  "Look closer. You're doing better than you think.",
  "You deserve kindness, not critique.",
  "Bare-faced or full glam, you're worth looking at.",
  "Your skin is a work in progress, and that's okay.",
  "Some days are good skin days. This can be one.",
  "You're not behind, you're just getting started.",
  "Texture, pores, and all, you're still worth it.",
  "Confidence looks better than any product ever will.",
  "Your skin doesn't have to be perfect to be yours.",
  "Take a second. You look good today.",
  "Progress on your skin is still progress.",
  "Your face has earned some patience today.",
  "You're allowed to feel pretty on an off day.",
  "You get the final say, not the mirror.",
  "Your skin's healing, even on days it doesn't show.",
  "You don't need a filter to feel like yourself.",
  "Small steps, same face, still worth it.",
  "Your skin is yours to love, not to fix.",
  "Bad skin day, still a good you day.",
  "You're glowing in ways a mirror can't always catch.",
  "You've been trying, and it shows.",
  "You're worth showing up for, breakouts and all.",
];
