"""add water goal fields to preferences and water intakes table

Revision ID: 038bf540767a
Revises: 320b1044102c
Create Date: 2026-08-06 21:12:51.593678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038bf540767a'
down_revision: Union[str, Sequence[str], None] = '320b1044102c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_intakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('oz', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_water_intake_user_date')
    )
    op.create_index(op.f('ix_water_intakes_date'), 'water_intakes', ['date'], unique=False)
    op.create_index(op.f('ix_water_intakes_id'), 'water_intakes', ['id'], unique=False)
    op.create_index(op.f('ix_water_intakes_user_id'), 'water_intakes', ['user_id'], unique=False)
    op.add_column('user_preferences', sa.Column('water_goal_oz', sa.Integer(), nullable=True))
    op.add_column('user_preferences', sa.Column('water_weight_lb', sa.Float(), nullable=True))
    op.add_column('user_preferences', sa.Column('water_activity_level', sa.String(), nullable=True))
    op.add_column('user_preferences', sa.Column('water_climate', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'water_climate')
    op.drop_column('user_preferences', 'water_activity_level')
    op.drop_column('user_preferences', 'water_weight_lb')
    op.drop_column('user_preferences', 'water_goal_oz')
    op.drop_index(op.f('ix_water_intakes_user_id'), table_name='water_intakes')
    op.drop_index(op.f('ix_water_intakes_id'), table_name='water_intakes')
    op.drop_index(op.f('ix_water_intakes_date'), table_name='water_intakes')
    op.drop_table('water_intakes')
    # ### end Alembic commands ###
