"""add pao_months column to products

Revision ID: 1be7d4a74e9f
Revises: 5bd703a8831d
Create Date: 2026-06-12 01:09:47.248828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be7d4a74e9f'
down_revision: Union[str, Sequence[str], None] = '5bd703a8831d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('pao_months', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'pao_months')
    # ### end Alembic commands ###
