"""add home_routine_id to user preferences

Revision ID: 320b1044102c
Revises: cdf7657b99a9
Create Date: 2026-08-06 20:04:05.701427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '320b1044102c'
down_revision: Union[str, Sequence[str], None] = 'cdf7657b99a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('home_routine_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_user_preferences_home_routine_id_routines'), 'user_preferences', 'routines', ['home_routine_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_preferences_home_routine_id_routines'), 'user_preferences', type_='foreignkey')
    op.drop_column('user_preferences', 'home_routine_id')
    # ### end Alembic commands ###
