"""add opened_date alerts and device tokens

Revision ID: 44b29a4ab2e5
Revises: 5ed147498d81
Create Date: 2026-08-02 20:16:03.054922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44b29a4ab2e5'
down_revision: Union[str, Sequence[str], None] = '5ed147498d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_device_tokens_id'), 'device_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.add_column('alerts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('alerts', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('title', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('body', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('scheduled_for', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.add_column('alerts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('alerts', 'alert_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.drop_constraint(op.f('alerts_scan_id_fkey'), 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'alerts', 'users', ['user_id'], ['id'])
    op.drop_column('alerts', 'scan_id')
    op.add_column('products', sa.Column('opened_date', sa.Date(), nullable=True))
    op.add_column('products', sa.Column('expiry_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_products_expiry_date'), 'products', ['expiry_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_expiry_date'), table_name='products')
    op.drop_column('products', 'expiry_date')
    op.drop_column('products', 'opened_date')
    op.add_column('alerts', sa.Column('scan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_foreign_key(op.f('alerts_scan_id_fkey'), 'alerts', 'scan_results', ['scan_id'], ['id'])
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.alter_column('alerts', 'alert_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('alerts', 'created_at')
    op.drop_column('alerts', 'is_read')
    op.drop_column('alerts', 'scheduled_for')
    op.drop_column('alerts', 'body')
    op.drop_column('alerts', 'title')
    op.drop_column('alerts', 'product_id')
    op.drop_column('alerts', 'user_id')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    # ### end Alembic commands ###
