"""add user_id to products

Revision ID: 9660ec22fff6
Revises: 49e54a2f8d97
Create Date: 2026-04-11 23:34:17.284526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9660ec22fff6'
down_revision: Union[str, Sequence[str], None] = '49e54a2f8d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'user_id')
    # ### end Alembic commands ###
