"""add_is_sensitive_to_skin_profiles

Revision ID: e8290c9acdd9
Revises: da4a39b9187c
Create Date: 2026-07-07 21:28:14.629412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8290c9acdd9'
down_revision: Union[str, Sequence[str], None] = 'da4a39b9187c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skin_profiles', sa.Column('is_sensitive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skin_profiles', 'is_sensitive')
    # ### end Alembic commands ###
