"""add routine step completions and user preferences

Revision ID: e9925c4b83ba
Revises: 44b29a4ab2e5
Create Date: 2026-08-02 23:00:42.619061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9925c4b83ba'
down_revision: Union[str, Sequence[str], None] = '44b29a4ab2e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('water_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('water_reminder_time', sa.String(), nullable=False),
    sa.Column('routine_digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('routine_step_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('completed_on', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['routine_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'step_id', 'completed_on', name='uq_user_step_date')
    )
    op.create_index(op.f('ix_routine_step_completions_completed_on'), 'routine_step_completions', ['completed_on'], unique=False)
    op.create_index(op.f('ix_routine_step_completions_id'), 'routine_step_completions', ['id'], unique=False)
    op.create_index(op.f('ix_routine_step_completions_routine_id'), 'routine_step_completions', ['routine_id'], unique=False)
    op.create_index(op.f('ix_routine_step_completions_user_id'), 'routine_step_completions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routine_step_completions_user_id'), table_name='routine_step_completions')
    op.drop_index(op.f('ix_routine_step_completions_routine_id'), table_name='routine_step_completions')
    op.drop_index(op.f('ix_routine_step_completions_id'), table_name='routine_step_completions')
    op.drop_index(op.f('ix_routine_step_completions_completed_on'), table_name='routine_step_completions')
    op.drop_table('routine_step_completions')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
