"""add ingredient analysis cache to scan_results

Revision ID: fe1f4f9f01f1
Revises: 7933b91ea854
Create Date: 2026-08-16 17:44:46.194095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1f4f9f01f1'
down_revision: Union[str, Sequence[str], None] = '7933b91ea854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_results', sa.Column('ingredient_analysis', sa.JSON(), nullable=True))
    op.add_column('scan_results', sa.Column('ingredient_analysis_skin_type', sa.String(), nullable=True))
    op.add_column('scan_results', sa.Column('ingredient_analysis_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_results', 'ingredient_analysis_updated_at')
    op.drop_column('scan_results', 'ingredient_analysis_skin_type')
    op.drop_column('scan_results', 'ingredient_analysis')
    # ### end Alembic commands ###
